    - name: Distribution
      debug: msg="{{ ansible_distribution }}"

    - name: pause
      pause:
        seconds: 10

    - name: Alpine Set the timezone alpine
      become: true
      file:
        src: /usr/share/zoneinfo/America/New_York
        dest: /etc/localtime
        state: link
      when: inventory_hostname in groups['new_alpine_container']

    - name: Set the timezone debian
#      become: true
      ansible.builtin.timezone:
        name: America/New_York
      when: ansible_distribution != 'Alpine' 
