---
- hosts: all
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    
    - name: update apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu'

    - name: git clone https://github.com/mdriesnj/dotfiles
      ansible.builtin.git:
        repo: https://github.com/mdriesnj/dotfiles
        dest: /home/mdries/dotfiles
#        version: master

    - name: Remove file zshrc
      ansible.builtin.file:
        path: /home/mdries/.zshrc
        state: absent

    - name: Remove file vimrc
      ansible.builtin.file:
        path: /home/mdries/.vimrc
        state: absent

    - name: Symlink zshrc
      ansible.builtin.file:
        src: /home/mdries/dotfiles/.zshrc
        dest: /home/mdries/.zshrc
        owner: mdries
        group: mdries
        state: link
        
    - name: Symlink vimrc
      ansible.builtin.file:
        src: /home/mdries/dotfiles/.vimrc
        dest: /home/mdries/.vimrc
        owner: mdries
        group: mdries
        state: link
