---
- hosts: all
  
  tasks:
    become: true

    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu'

    - name: git clone https://github.com/mdriesnj/dotfiles
      git: 
        repo: https://github.com/mdriesnj/dotfiles
        dest: /home/mdries/
        version: master
