---
- hosts: all
  tasks:
    - include_tasks: tasks-update-packages.yml
    - include_tasks: tasks-newuser.yml
    - include_tasks: tasks-standard-packages.yml
    - include_tasks: tasks-dotfiles.yml
    - include_tasks: tasks-update-sshd_config.yml
