#install python first https://docs.ansible.com/ansible/latest/os_guide/intro_bsd.html

---
- hosts: all

  become_method: su
  become: true
  tasks:
    - name: ensure nginx is up to date
      community.general.openbsd_pkg:
        name: nginx
        state: latest
