#install python first https://docs.ansible.com/ansible/latest/os_guide/intro_bsd.html

---
- hosts: all

  become: true
  tasks:
    - name: Update all packages on the system
      community.general.openbsd_pkg:
        name: '*'
        state: latest

    - name: Apply all available system patches
      community.general.syspatch:

    - name: Reboot if patch requires it
      ansible.builtin.reboot:
      when: syspatch.reboot_needed
