---
- hosts: all

  become: true
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Debian'

    - name: update yum package
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'PMX'
