---
- hosts: new_vm
  vars:

  tasks:
    - include_tasks: tasks-update-packages.yml
    - include_tasks: tasks-standard-packages.yml
    - include_tasks: tasks-dotfiles.yml
    
#    - include_tasks: tasks-timezone.yml
    - include_tasks: tasks-sshd-config.yml
    - include_tasks: tasks-disable-root.yml  
    - include_tasks: task-crontab-caches.yml
#    - include_tasks: tasks-reboot.yml
