---
- hosts: all
  vars:
    # Setting this for unarchive to work
    ansible_remote_tmp: /tmp
    justdotfiles: false
    
  tasks:
    - include_tasks: tasks-update-packages.yml
    - include_tasks: tasks-newuser.yml
    - include_tasks: tasks-standard-packages.yml
    - include_tasks: tasks-new-dotfiles.yml
    - include_tasks: tasks-sshd-config.yml
  #  - include_tasks: tasks-disable-root.yml
    - include_tasks: tasks-add-ping-cap.yml
    - include_tasks: tasks-timezone.yml
    - include_tasks: tasks-services.yml
#    - include_tasks: tasks-snap-lxc.yml
#    - name: Unconditionally reboot the machine with all defaults
#      reboot:
#        connect_timeout: 60
#        reboot_timeout: 30
