---
- hosts: normal
  vars:
    # Setting this for unarchive to work
    #ansible_remote_tmp: /tmp
    #firstrun: true
    #ansible_become_password: "{{ password | password_hash('sha512') }}"
    net.ipv6.conf.all.disable_ipv6: 1
    net.ipv6.conf.default.disable_ipv6: 1
    net.ipv6.conf.lo.disable_ipv6: 1
    net.ipv6.conf.tun0.disable_ipv6: 1
   
  tasks:
    - include_tasks: tasks-update-packages.yml
 
