    - name: update dockers
      ansible.builtin.command: /home/mdries/update-dockers.sh
#      args:
#        chdir: /home/mdries/changedetection
      when: inventory_hostname in groups['normal']
 
