    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    
#    - name: update apt packages
#      apt:
#        upgrade: yes
#        update_cache: yes
#      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu'


    - name: root Download Oh My Zsh installation script
      become: true
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh
        mode: 0755
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"


#-------------------- root dotfiles-----------------------------
    - name: root Run Oh My Zsh installation script
      become: yes
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"
      

    - name: root git clone https://github.com/mdriesnj/dotfiles
      become: true
      ansible.builtin.git:
        repo: https://github.com/mdriesnj/dotfiles
        dest: /root/dotfiles
#        version: master
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"

      
    - name: root Remove file zshrc
      become: true
      ansible.builtin.file:
        path: /root/.zshrc
        state: absent
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"
      
    - name: root Remove file vimrc
      become: true
      ansible.builtin.file:
        path: /root/.vimrc
        state: absent
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"
      
    - name: root Symlink zshrc
      become: true
      ansible.builtin.file:
        src: /root/dotfiles/.zshrc
        dest: /root/.zshrc
        owner: root
        group: root
        state: link
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"
      
    - name: root Symlink vimrc
      become: true
      ansible.builtin.file:
        src: /root/dotfiles/.vimrc
        dest: /root/.vimrc
        owner: root
        group: root
        state: link
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"
      
    - name: root change user shell to zsh 
      become: yes
      user:
        name: root
        shell: /bin/zsh
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"


#-------------------- mdries dotfiles-----------------------------
    - name: chown mdries
      become: true
      file:
        path: /home/mdries
        state: directory
        recurse: yes
        owner: mdries
        group: mdries
      when: justdotfiles == false  
    
    - name: mdries Run Oh My Zsh installation script
#      become_user: mdries
#      become_user: mdries
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"
      when: (ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux") and justdotfiles == true


#    - name: install omz as mdries
#      shell: su mdries sh -c /tmp/install_ohmyzsh.sh --unattended
#      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"

#    - name: install omz as mdries
#      command: "sudo -i -u mdries sh -c /tmp/install_ohmyzsh.sh --unattended"
#      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"

    - name: make /home/mdries/.oh-my-zsh
      file:
        path: /home/mdries/.oh-my-zsh
        state: directory
        mode: '0700'
      when: justdotfiles == false

    - name: copy oh-my-zsh
      become: true
      copy: src=/root/.oh-my-zsh/ dest=/home/mdries/.oh-my-zsh/ remote_src=yes directory_mode=yes
      when: justdotfiles == false

    - name: git clone mdries https://github.com/mdriesnj/dotfiles
      ansible.builtin.git:
        repo: https://github.com/mdriesnj/dotfiles
        dest: /home/mdries/dotfiles/
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"
#        version: master

    - name: Remove mdries file zshrc
      become: true
      become_user: mdries
      ansible.builtin.file:
        path: /home/mdries/.zshrc
        state: absent
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"

    - name: Remove mdries file vimrc
      become: true
      become_user: mdries
      ansible.builtin.file:
        path: /home/mdries/.vimrc
        state: absent
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"
      
    - name: Symlink mdries zshrc
      become: true
      become_user: mdries
      ansible.builtin.file:
        src: /home/mdries/dotfiles/.zshrc
        dest: /home/mdries/.zshrc
        owner: mdries
        group: mdries
        state: link
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"
      
    - name: Symlink mdries vimrc
      become: true
      become_user: mdries
      ansible.builtin.file:
        src: /home/mdries/dotfiles/.vimrc
        dest: /home/mdries/.vimrc
        owner: mdries
        group: mdries
        state: link
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =="AlmaLinux"

    - name: chown mdries
      become: true
      file:
        path: /home/mdries
        state: directory
        recurse: yes
        owner: mdries
        group: mdries
        
