#     - name: Distribution
#       debug: msg="{{ ansible_distribution }}"
    - name: crontab caches
      become: true
      ansible.builtin.cron:
        name: clear caches every hour
        special_time: hourly
        job: "sync; echo 1 > /proc/sys/vm/drop_caches"
