    - name: Distribution
      debug: msg="{{ ansible_distribution }}"

      
    - name: update apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu'

    - name: update yum package
      become: true
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'AlmaLinux'


    - name: upgrade all packages
      become: true
      command: "pkg_add -u -Dsnap"
      when: ansible_distribution == 'OpenBSD'

#    - name: Apply all patches and store result
#      become: true
#      community.general.syspatch:
#      register: syspatch
#      when: ansible_distribution == 'OpenBSD' 
    - name: reboot host
      reboot:
        msg: "rebooting into bsd.rd to upgrade"
        reboot_timeout: 90

#    - name: Reboot if patch requires it
#      become: true
#      ansible.builtin.reboot:
#      when: ansible_distribution == 'OpenBSD' and syspatch.reboot_needed

