    - name: configure sshd
      become: true
      lineinfile:
        path: "/etc/ssh/sshd_config"
        #regex: "^(#)?{{item.key}}"
        regex: ^(# *)?{{item.key}}
        line: "{{item.key}} {{item.value}}"
        #state: present
      loop:
        - { key: "PermitRootLogin", value: "no" }
        - { key: "Protocol", value: "2" } 
        - { key: "HostBasedAuthentication", value: "no" } 
        - { key: "IgnoreRHosts", value: "yes" }
        - { key: "AuthorizedKeysFile", value: ".ssh/authorized_keys" } 
        - { key: "PubkeyAuthentication", value: "yes" }
        - { key: "MaxAuthTries", value: "3" }
        - { key: "PermitUserEnvironment", value: "no" } 
        - { key: "UsePAM", value: "yes" }
        - { key: "X11Forwarding", value: "no" } 
        - { key: "AllowTcpForwarding", value: "no" } 
        - { key: "PermitEmptyPasswords", value: "no" }
        - { key: "AllowUsers", value: "mdries root" } 
        - { key: "Port", value: "22" } 

#    - name: configure sshd socket port
#      become: true
#      lineinfile:
#        path: "/etc/systemd/system/sockets.target.wants/ssh.socket"
        #regex: "^(#)?{{item.key}}"
#        regex: ^(# *)?{{item.key}}
#        line: "ListenStream=22"
        #state: present
 #     loop:
 #       - { key: "ListenStream", value: "22" }

    
    - name: systemd stuff
      become: true
#      systemd:
#        daemon_reload: yes
      systemd:
        name: sshd
        state: restarted
      when: ansible_distribution == 'Debian' or ansible_distribution =='Ubuntu' or ansible_distribution =='AlmaLinux'
    
    - name: openbsd sshd restart 
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: ansible_distribution == 'OpenBSD'



#      systemd:
#        name: systemd-logind
#        masked: no
#        state: started

 #   - name: Unconditionally reboot the machine with all defaults
 #     reboot:


#        masked: yes
#        enabled: no
#        name: sshd.socket
#        masked: yes
#        name: sshd
#        enabled: no
#        name: ssh
#        enabled: yes
