    - name: update mgmt ansible
      ansible.builtin.command: /home/mdries/update.sh
#      args:
#        chdir: /home/mdries/changedetection
      when: inventory_hostname in groups['changedetection']
 
