    - name: update mgmt ansible
      ansible.builtin.command: update.sh
      become: yes
      args:
        chdir: /home/mdries/changedetection
      when: inventory_hostname in groups['changedetection']
 
