    - name: Distribution
      debug: msg="{{ ansible_distribution }}"

    - name: Set the timezone alpine
#      become: true
      timezone:
        name: America/New_York
      when: ansible_distribution == 'Alpine' and firstrun == true

    - name: Set the timezone debian
#      become: true
      ansible.builtin.timezone:
        name: America/New_York
      when: firstrun == false
